kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: wtf-route
  namespace: kianfarah-dev
  labels:
    app: wtf
spec:
  to:
    kind: Service
    name: wtf
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
wildcardPolicy: None

